### ISSUE TITLE
missing `volume_type` (`volume_` typo) in block_device_mappings

### ISSUE THREAD

**Issue by zaksamalik** [cloudposse/terraform-aws-ecs-cluster#6]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
`volume_type` is missing from `block_device_mappings`. Assuming typo is `volume_` input. Also missing `throughput` input. Will put up PR with updated code once https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/97 is merged using the new version tag. The referenced PR adds `throughput` input to the autoscale group.

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by esolitos** [comment]
It seems that a wild `sed` command was issued, because I ca see the same problem with:
- [ ] `instance_market_options` lists `market_` but should be => `market_type`
- [ ] `instance_market_options` lists `spot_instance_` but should be => `spot_instance_type`

I'll open a PR for this. :)
